routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\DestinationController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\SettingController;

// Frontend Routes

Route::get('/index.html', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/about.html', function () {
    return view('frontend.about');
});
Route::get('/travel_destination.html/{destination:city}', [\App\Http\Controllers\DetailController::class, 'show'])->name('destination.show');
Route::get('/travel_destination.html', function () {
    return view('frontend.destination.index');
});
Route::get('/contact.html', function () {
    return view('frontend.contact');
});

Auth::routes();

// Admin Routes
Route::group(['middleware' => 'isAdmin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::resource('permissions', PermissionController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::get('profile', [ProfileController::class, 'show'])->name('profile.show');
    Route::put('profile', [ProfileController::class, 'update'])->name('profile.update');
    
    Route::resource('sliders', SliderController::class);
    Route::resource('destinations', DestinationController::class);
    Route::resource('testimonials', TestimonialController::class);
    Route::resource('settings', SettingController::class);
});

app/Models/Destination.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Destination extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function sliders()
    {
        return $this->hasMany(Slider::class);
    }
}

app/Http/Controllers/Admin/DestinationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Destination;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use App\Http\Requests\Admin\DestinationRequest;

class DestinationController extends Controller
{
   
    public function index(): View
    {
        $destinations = Destination::get();

        return view('admin.destinations.index', compact('destinations'));
    }

    public function create(): View
    {
        return view('admin.destinations.create');
    }
    
    public function show(Destination $destination)
    {
        return view('frontend.destination.show', compact('destination'));
    }

    public function store(DestinationRequest $request): RedirectResponse
    {
        if($request->validated()){
            $image = $request->file('image')->store('assets/destination', 'public');
            Destination::create($request->except('image')+['image'=>$image]);

        }
        
        return redirect()->route('admin.destinations.index')->with([
            'message' => 'successfully created !',
            'alert-type' => 'success'
        ]);
    }

    public function edit(Destination $destination): View
    {
        return view('admin.destinations.edit', compact('destination'));
    }

    public function update(DestinationRequest $request, Destination $destination): RedirectResponse
    {
        if($request->validated()){
            if($request->image){
                File::delete('storage/' . $destination->image);
                $image = $request->file('image')->store('assets/destination', 'public');
                $destination->update($request->except('image')+['image'=>$image]);
            }else{
                $destination->update($request->validated());
            }
        }
        

        return redirect()->route('admin.destinations.index')->with([
            'message' => 'successfully updated !',
            'alert-type' => 'info'
        ]);
    }

    public function destroy(Destination $destination): RedirectResponse
    {
        File::delete('storage/' . $destination->image);
        $destination->delete();

        return back()->with([
            'message' => 'successfully deleted !',
            'alert-type' => 'danger'
        ]);
    }
}

resources/views/admin/destinations/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
        <div class="card shadow">
            <div class="card-header">
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">{{ __('create destination') }}</h1>
                    <a href="{{ route('admin.destinations.index') }}" class="btn btn-success btn-sm shadow-sm">{{ __('Go Back') }}</a>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('admin.destinations.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="city">{{ __('city') }}</label>
                        <input type="text" class="form-control" id="city" placeholder="{{ __('city') }}" name="city" value="{{ old('city') }}" />
                    </div>
                    <div class="form-group">
                        <label for="province">{{ __('province') }}</label>
                        <input type="text" class="form-control" id="province" placeholder="{{ __('province') }}" name="province" value="{{ old('province') }}" />
                    </div>
                    <div class="form-group">
                        <label for="price">{{ __('price') }}</label>
                        <input type="number" class="form-control" id="price" placeholder="{{ __('price') }}" name="price" value="{{ old('price') }}" />
                    </div>
                    <div class="form-group">
                        <label for="duration">{{ __('duration') }}</label>
                        <input type="text" class="form-control" id="duration" placeholder="{{ __('duration') }}" name="duration" value="{{ old('duration') }}" />
                    </div>
                    <div class="form-group">
                        <label for="number">{{ __('number') }}</label>
                        <input type="number" class="form-control" id="number" placeholder="{{ __('number') }}" name="number" value="{{ old('number') }}" />
                    </div>
                    <div class="form-group">
                        <label for="image">{{ __('image') }}</label>
                        <input type="file" class="form-control" id="image" placeholder="{{ __('image') }}" name="image" value="{{ old('image') }}" />
                    </div>
                    <div class="form-group">
                        <label for="description">{{ __('description') }}</label>
                        <textarea name="description" id="description" class="form-control" cols ="30" rows="10">{{ old('description') }}</textarea>
                    </div>
                    
                    <button type="submit" class="btn btn-success">{{ __('Save') }}</button>
                </form>
            </div>
        </div>
    

    <!-- Content Row -->

</div>
@endsection

@push('style-alt')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endpush

@push('script-alt')
<script
        src="https://code.jquery.com/jquery-3.6.3.min.js"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
        crossorigin="anonymous"
    >
    </script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
      $('.select-multiple').select2();
</script>
@endpush

resources/views/admin/destinations/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">

<!-- Content Row -->
        <div class="card shadow">
            <div class="card-header">
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">{{ __('edit destination')}}</h1>
                    <a href="{{ route('admin.destinations.index') }}" class="btn btn-success btn-sm shadow-sm">{{ __('Go Back') }}</a>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('admin.destinations.update', $destination->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="form-group">
                        <label for="city">{{ __('city') }}</label>
                        <input type="text" class="form-control" id="city" placeholder="{{ __('city') }}" name="city" value="{{ old('city', $destination->city) }}" />
                    </div>
                    <div class="form-group">
                        <label for="province">{{ __('province') }}</label>
                        <input type="text" class="form-control" id="province" placeholder="{{ __('province') }}" name="province" value="{{ old('province', $destination->province) }}" />
                    </div>
                    <div class="form-group">
                        <label for="price">{{ __('price') }}</label>
                        <input type="number" class="form-control" id="price" placeholder="{{ __('price') }}" name="price" value="{{ old('price', $destination->price) }}" />
                    </div>
                    <div class="form-group">
                        <label for="duration">{{ __('duration') }}</label>
                        <input type="text" class="form-control" id="duration" placeholder="{{ __('duration') }}" name="duration" value="{{ old('duration', $destination->duration) }}" />
                    </div>
                    <div class="form-group">
                        <label for="number">{{ __('number') }}</label>
                        <input type="number" class="form-control" id="number" placeholder="{{ __('number') }}" name="number" value="{{ old('number', $destination->number) }}" />
                    </div>
                    <div class="form-group">
                        <label for="image">{{ __('image') }}</label>
                        <input type="file" class="form-control" id="image" placeholder="{{ __('image') }}" name="image" value="{{ old('image') }}" />
                    </div>
                    <div class="form-group">
                        <label for="description">{{ __('description') }}</label>
                        <textarea name="description" id="description" class="form-control" cols ="30" rows="10">{{ old('description', $destination->description) }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-success">{{ __('Save')}}</button>
                </form>
            </div>
        </div>
    

    <!-- Content Row -->

</div>
@endsection


@push('style-alt')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endpush

@push('script-alt')
<script
        src="https://code.jquery.com/jquery-3.6.3.min.js"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
        crossorigin="anonymous"
    >
    </script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
      $('.select-multiple').select2();
</script>
@endpush

resources/views/admin/destinations/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <!-- Content Row -->
        <div class="card">
            <div class="card-header py-3 d-flex">
                <h6 class="m-0 font-weight-bold text-gray">
                    {{ __('Destination Data') }}
                </h6>
                <div class="ml-auto">
                    <a href="{{ route('admin.destinations.create') }}" class="btn btn-success">
                        <span class="icon text-white-50">
                            <i class="fa fa-plus"></i>
                        </span>
                        <span class="text">{{ __('New Destination') }}</span>
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="data-table" class="table table-bordered table-striped table-hover datatable datatable-role" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th width="10">

                                </th>
                                <th>No</th>
                                <th>{{ __('Image') }}</th>
                                <th>{{ __('City') }}</th>
                                <th>{{ __('Province') }}</th>
                                <th>{{ __('Price') }}</th>
                                <th>{{ __('Duration') }}</th>
                                <th>{{ __('Action') }}</th>
                            </tr>
                        </thead>
                        </thead>
                        <tbody>
                            @forelse($destinations as $destination)
                            <tr data-entry-id="{{ $destination->id }}">
                                <td>

                                </td>
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    <a target="_blank" href="{{ Storage::url($destination->image) }}">
                                        <img src="{{ Storage::url($destination->image) }}" width="100" alt="">
                                    </a>
                                </td>
                                <td>{{ $destination->city }}</td>
                                <td>{{ $destination->province }}</td>
                                <td>{{ $destination->price }}</td>
                                <td>{{ $destination->duration }}</td>
                                
                                <td>
                                    <div class="btn-group btn-group-sm">
                                        <a target="_blank" href="{{ route('admin.destinations.edit', $destination->id) }}" class="btn btn-info">
                                            <i class="fa fa-pencil-alt"></i>
                                        </a>
                                
                                        <form onclick="return confirm('are you sure ? ')" class="d-inline" action="{{ route('admin.destinations.destroy', $destination->id) }}" method="POST">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-danger" style="border-top-left-radius: 0;border-bottom-left-radius: 0;">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="7" class="text-center">{{ __('Data Empty') }}</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    <!-- Content Row -->

</div>
@endsection


@push('style-alt')
  <!-- DataTables -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css">
@endpush

@push('script-alt') 
    <script
        src="https://code.jquery.com/jquery-3.6.3.min.js"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
        crossorigin="anonymous"
    >
    </script>
    <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script>
    $("#data-table").DataTable();
    </script>
@endpush